
default: &default
    adapter: postgresql
    encoding: unicode
    database: money
    host: localhost
    pool: 5
    username: postgres
    password: postgres


development:
  <<: *default
  database: money

test: &test
  <<: *default
  database: test

production:
  <<: *default
  database: money_production
  username: postgres
  password: postgres

cucumber:
  <<: *test
